---
title: 'caspr: Cellular Automata for Spatial Pressure in R'
author: "Florian D. Schneider"
date: '`r Sys.Date()`'
output: 
  output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{caspr: Cellular Automata for Spatial Pressure in R}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
---

# General information

The caspr package is running spatial disturbance models in a cellular automata framework. This is part of a collaborative project between the group of [Sonia Kéfi](http://sonia.kefi.fr/) (Institut de Sciences d'Evolution, CNRS, IRD, Université Montpellier, France) and [Vishwesha Guttal](https://teelabiisc.wordpress.com/) (Center for Ecological Sciences, Indian Institute of Science, Bangalore, India).

## Contributors

Alain Danet, Alex Genin, Vishwesha Guttal, Sonia Kefi, Sabiha Majumder, Sumithra Sankaran, [Florian Schneider (Maintainer)](mailto:florian.schneider@univ-montp2.fr)

## Install package

The package can be installed directly from GitHub using the `devtools` package. 

```
install.packages("devtools")
devtools::install_github("fdschneider/caspr")
```

## License

The MIT License (MIT)

Copyright (c) 2015 the authors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.


# Package structure

The R-package is build around objects of a particular class `ca_model` (S3 objects in R) that contain all the model specific information, like the original publication, the update functions, and the cell states. 
These objects can be handled by a function called `ca()` which runs the cellular automata over time. 
Other functions allow the plotting of single snapshots or timeseries, the generation of initial lattices/grids/landscapes, the calculation of spatial and temporal indicators as provided by the package ['spatialwarnings'](https://github.com/fdschneider/spatial_warnings).

## Cellular automata



## Objects and functions

In the following the objects and functions are described in a (somewhat) logical sequence of usage. 

### landscape objects

Cellular automata are lattice- or grid-based systems, where neighboring cells on the lattice are affecting each others transition rules. Those lattices are termed 'landscapes' within the framework of 'caspr' and are stored in objects of class `"landscape"`. 

A landscape object is a list `l` that contains

- `l$dim` : a named vector of the default form `c(width = 50, height = 50)`
- `l$cells` : a factorial vector of length `prod(l$dims)` that contains the state that each cell of the landscape matrix is in (row-wise from top to bottom). 

Specific method for functions `plot`, `summary` and `print` do exist, which means you can call:

```
l
plot(l)
summary(l)
```

The vectorial storage of the grid is allowing for a more efficient memory use and evaluation than with matrices, using map vectors that are provided as global variables by executing `mapping(l$dims[1], l$dims[2])`. 
For compatibility the landscape object can be translated into a matrix using `as.matrix(l)`. Any matrix of factorial content can be reverted into a landscape object using `as.landscape(l, states)`. 
### Generate landscape objects 

**Usage:** `init_landscape(states, cover, width, height)`

landscape objects are created using the function `init_landscape()` , e.g. 

```
l <- init_landscape(c("1", "0"), c(0.2,0.8), width = 100)
``` 

Landscapes are squared by default, but a height argument can be specified. However, doing so **will disqualify the output to be analysed spatially!!!** 

### Model objects

A model object is a list `model` of class `"ca_model"` that contains

- `model$name`: the name of the model
- `model$ref`: the original reference
- `model$states`: the potential cell states
- `model$cols`: colors for cell states
- `model$interact` : an interaction matrix, defaults to 4-cell neighborhood, affects behaviour of count function. 
- `model$parms`: a template for parameters including default parameters 
- `model$update`: the update function, which takes a landscape object `x_old` and returns a landscape object `x_new`, representing the updating of one single timestep

Other functions or static parameters can be provided as further objects to the list. But those listed abova are mandatory. 
In the current version of *caspr*, the objects of class `ca_model` are not created by a function, but provided manually as custom R objects. If you add a model than start from `model_template.R`! Before running `ca(l, yourmodel)`  you should test the update function for valid output and optimize for evaluation speed!

A method `print.ca_model` exists which allows to review a model's specifications simply by calling the model object in R.

### Running models

The function `ca(x, model, parms)` runs a cellular automata simulation starting from the landscape object provided in `x` and using the update function provided by `model` with the parameter set `parms` (a list of parameters). Before running the model, the function validates the parameter set provided against the template stored in `model$parms`. 

Further parameters are available to adjust the timespan run and the snapshots of the landscape saved. 

```
l <- init_landscape(c("+", "0", "-"), c(0.2,0.7,0.1))
p <- list(d = 0.4, r = 0.2, delta = 0.4) 
r <- ca(l, musselbed, p)

```

After simulation, the function returns an object of class `ca_results`. The result object `r` has the structure:

- `r$model`: the `ca_model` object used to run the simulation, including the provided parameter set.
- `r$time`: a vector of the distinct timesteps of the simulation
- `r$evaluate`: the begin and end of a steady state period in the simulation run. 
- `r$cover`: a data frame reporting the global cover with one column for each state of the model and one row for each timestep. Thus, `r$cover[1]` returns the timeseries of the primary cell state. 
- `r$local`: a data frame reporting the average local cover of the cell states, i.e. the average probability that a state *i* is found in the neighborhood given that the focal cell is in state *i*. Thus, `r$local[1]` returns the timeseries of the primary cell state. 
- `r$snapshots`: a registry table of the snapshots and at which point in time they were taken. 
- `r$landscapes`: a list of landscape objects for the given snapshots.
- `r$steadyness` : the difference in mean of the last and second-last period of length `t_eval`, as specified. 

Thus the result of a simulation contains two major types of output: 

1. the full timeseries of cover of each state (`r$cover`), as well as a timeseries of the average local cover (`r$local`). 
2. selected snapshots of the full landscape (`r$landscapes`). 

The length of both depends on the number of timesteps that were evaluated until the model terminated.

#### defining number of timesteps and saving snapshots of simulation run

There are two ways of specifying the number of timesteps, i.e. the duration of a simulation run. 

- define a fixed period of time
- run until a predefined criterion for steady state is reached



#### function `carray()`

A wrapper function that runs a model along a gradient of one parameter value or an array of parameter values making use of a parallel backend provided by the `foreach` package. The initial landscape is drawn for each replicate using the numerical vector of initial cover `init`. 

```r
p <- list(
    r = 0.4, # recolonisation of empty sites dependent on local density
    d = seq(0,1,0.1), # wave disturbance
    delta = 0.01, # intrinsic disturbance rate
    replicates = 1:5
  )
r <- carray(musselbed, c(0.7,0.15,0.15), parms = p)

```

It returns a dataframe with global and local cover for each state for each parameter value or combination of parameter values given in `parms`.



#### function `animate()`



## Model descriptions

A set of spatially-explicit cellular automata is provided with caspr. They have in common that a spatially explicit stress is acting on the focal cell state, for instance by increasing mortality if predators or gaps in the canopy are present or by reducing mortality by associational growth.  
We also added Conway's Game of Life as a test case for animation functions -- and for fun. 

### Mussel bed model

### Forest Gap model

### Predator-prey model

### Grazing model

### Conway's Game of Life


## Spatial indicators
