// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// randn
int randn(double min, double max);
RcppExport SEXP caspr_randn(SEXP minSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type min(minSEXP);
    Rcpp::traits::input_parameter< double >::type max(maxSEXP);
    __result = Rcpp::wrap(randn(min, max));
    return __result;
END_RCPP
}
// randp
double randp();
RcppExport SEXP caspr_randp() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(randp());
    return __result;
END_RCPP
}
// predprey_core
IntegerMatrix predprey_core(IntegerMatrix grid, int subs, int NEIGHBORS, double betaf, double betas, double delta);
RcppExport SEXP caspr_predprey_core(SEXP gridSEXP, SEXP subsSEXP, SEXP NEIGHBORSSEXP, SEXP betafSEXP, SEXP betasSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< int >::type subs(subsSEXP);
    Rcpp::traits::input_parameter< int >::type NEIGHBORS(NEIGHBORSSEXP);
    Rcpp::traits::input_parameter< double >::type betaf(betafSEXP);
    Rcpp::traits::input_parameter< double >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    __result = Rcpp::wrap(predprey_core(grid, subs, NEIGHBORS, betaf, betas, delta));
    return __result;
END_RCPP
}
