animate <- function(...) UseMethod("animate")

#' Create animated gif or video from simulation result. 
#'
#' @param x A ca_result object (generated by \code{ca()}) 
#' @param filename A character value specifying relative path and filename. File endings will be ignored and replaced by value in \code{type}.   
#' @param type A character value specifying the type of output. Either "gif" or "mp4". 
#' @param speed A numeric value specifying the speed of the output (defaults to 1). 
#'
#' @return Returns an animated gif or video. 
#' 
#' @details This requires R-package \link{[animation]} and the additional software \href{http://imagemagick.org/}{ImageMagick} (for animated .gif) and \href{https://ffmpeg.org/download.html}{FFMPEG} (for .mpeg videos). 
#' 
#' @seealso \link{animate.ca_model}
#' @export
#' @import animation
#' 
#' @examples
#' 
#' # 1. run simulation and save full landsape at each timestep. create animated gif.
#' 
#' l <- init_landscape(c("1","0"), c(0.6,0.4), 100)
#' r <- ca(l, model = life, t_max = 500, t_eval = 500, saveeach = 1)
#' animate(r, "life01.gif")

animate.ca_result <- function(x, filename, type = "gif", each = 1, speed = 1) {
  
  #get root of filename
  
  filename <- sub(".avi|.gif|.mpg|.mp4", "", filename)
  
  if(Sys.info()[['sysname']] == "Linux") X11.options(antialias = "none") #for Linux Systems to enable pixel-wise plotting in (animated) gif-files. 
  if(Sys.info()[['sysname']] == "Windows") windows.options(antialias = "none") #for Windows Systems to enable pixel-wise plotting in (animated) gif-files. 
  
  if("gif" %in% type) {
    
    saveGIF( 
      for(i in 1:length(x$landscapes) ) {
        par(mar = c(0,0,0,0))
        plot(x$landscapes[[i]], cols = x$model$cols, grid = FALSE, ani = TRUE) 
      }
      , movie.name = paste0(filename, ".gif"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = x$landscapes[[1]]$dim[1], 
      ani.height = x$landscapes[[1]]$dim[2], 
      outdir = getwd()
      )
  } 
  if("mp4" %in% type) {
    saveVideo( 
      for(i in 1:length(x$landscapes) ) {
          par(mar = c(0,0,0,0))
          plot(x$landscapes[[i]], cols = x$model$cols, grid = FALSE, ani = TRUE) 
        }, 
      video.name = paste0(filename, ".mp4"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = x$landscapes[[1]]$dim[1]*5, 
      ani.height = x$landscapes[[1]]$dim[2]*5, 
      outdir = getwd()
    )
  }
  if("avi" %in% type) {
    saveVideo( 
      for(i in 1:length(x$landscapes) ) {
        par(mar = c(0,0,0,0))
        plot(x$landscapes[[i]], cols = x$model$cols, grid = FALSE, ani = TRUE) 
      }
      , 
      video.name = paste0(filename, ".avi"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = x$landscapes[[1]]$dim[1]*5, 
      ani.height = x$landscapes[[1]]$dim[2]*5, 
      outdir = getwd()
    )
  }
  if("wmv" %in% type) {
    saveVideo( 
      for(i in 1:length(x$landscapes) ) {
        par(mar = c(0,0,0,0))
        plot(x$landscapes[[i]], cols = x$model$cols, grid = FALSE, ani = TRUE) 
      }
      , 
      video.name = paste0(filename, ".wmv"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = x$landscapes[[1]]$dim[1]*5, 
      ani.height = x$landscapes[[1]]$dim[2]*5, 
      outdir = getwd()
    )
  }
}



#' Create animated gif or video from model definitions.  
#'
#' @param x An object of class \code{ca_model}.
#' @param init Initial landscape object or cover. If cover is provided as a numerical vector of lengths \code{length(x$states)}, a new landscape object is generated. 
#' @param parms Parameter set for simulation. If not provided, defaults are taken from model specs.
#' @param filename A character value specifying relative path and filename. File endings will be ignored and replaced by value in \code{type}. 
#' @param type A character value specifying the type of output. Either "gif" or "mp4". 
#' @param speed A numeric value specifying the speed of the output (defaults to 1). 
#' @param each An integer value. Distance between timesteps to be saved. 
#' @param t_max An integer value. Maximum number of timesteps. Note that one animated gif can only take up to 400 images, thus if \code{t_max > each*400} the animation will be truncated. 
#' @param width An integer numer. Defaults to 50 and is ignored if a landscape object is provided in \code{init}.
#' @param height An integer numer. Defaults to 50 or to \code{width} if provided and is ignored if a landscape object is provided in \code{init}.
#'
#' @return Returns an animated gif or video. 
#' @export
#'
#' @examples
#' 
#' # 1. run simulation and save full landsape at each timestep. create animated gif.
#' 
#' animate(life, init_landscape(c("1","0"), c(0.6,0.4), 100), filename = "life01.gif")

animate.ca_model <- function(x, init, parms = x$parms, filename, type = "gif", each = 1, speed = 1, t_max = 400*each, width = 50, height = width) {
  
  # get initial landscape
  if("landscape" %in% class(init)) {
    l <- init
  } else {
    if(length(init) == length(x$states))  {
      l <- init_landscape(x$states, init, width, height) 
    } else { 
      stop("Provide valid landscape object or cover vector!")
    }
  } 
  
  ## is interaction matrix provided? if not defaults to four cell neighborhood.   
  if(is.null(x$interact)) {
    I <- matrix(c(0, 1, 0,  1, NA, 1, 0, 1, 0), ncol = 3, byrow = TRUE) 
  } else {
    I <- x$interact 
  }
  
  mapping(l$dim[1], l$dim[2], i_matrix = I )
  
  #get stem of filename
  filename <- sub(".avi|.gif|.mpg|.mp4", "", filename)
  
  if(Sys.info()[['sysname']] == "Linux") X11.options(antialias = "none") #for Linux Systems to enable pixel-wise plotting in (animated) gif-files. 
  if(Sys.info()[['sysname']] == "Windows") windows.options(antialias = "none") #for Windows Systems to enable pixel-wise plotting in (animated) gif-files. 
  
  if("gif" %in% type) {
    
    saveGIF( 
      for(i in 1:t_max) {
        par(mar = c(0,0,0,0))
        plot(l, cols = x$cols, grid = FALSE, ani = TRUE) 
        for(j in 1:each) l <- x$update(l, parms)
      }
      , movie.name = paste0(filename, ".gif"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = l$dim[1], 
      ani.height = l$dim[2], 
      outdir = getwd()
    )
  } 
  if("mp4" %in% type) {
    saveVideo( 
      for(i in 1:t_max) {
        par(mar = c(0,0,0,0))
        plot(l, cols = x$cols, grid = FALSE, ani = TRUE) 
        for(j in 1:each) l <- x$update(l, parms)
      }, 
      video.name = paste0(filename, ".mp4"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = l$dim[1]*5, 
      ani.height = l$dim[2]*5, 
      outdir = getwd()
    )
  }
  if("avi" %in% type) {
    saveVideo( 
      for(i in 1:t_max) {
        par(mar = c(0,0,0,0))
        plot(l, cols = x$cols, grid = FALSE, ani = TRUE) 
        for(j in 1:each) l <- x$update(l, parms)
      }
      , 
      video.name = paste0(filename, ".avi"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = l$dim[1]*5, 
      ani.height = l$dim[2]*5, 
      outdir = getwd()
    )
  }
  if("wmv" %in% type) {
    saveVideo( 
      for(i in 1:t_max) {
        par(mar = c(0,0,0,0))
        plot(l, cols = x$cols, grid = FALSE, ani = TRUE) 
        for(j in 1:each) l <- x$update(l, parms)
      }
      , 
      video.name = paste0(filename, ".wmv"), 
      img.name = "grid", 
      convert = "convert", 
      interval = 0.1/speed,
      cmd.fun = system, 
      clean = TRUE, 
      ani.width = l$dim[1]*5, 
      ani.height = l$dim[2]*5, 
      outdir = getwd()
    )
  }
}

