# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randn <- function(min, max) {
    .Call('caspr_randn', PACKAGE = 'caspr', min, max)
}

randp <- function() {
    .Call('caspr_randp', PACKAGE = 'caspr')
}

predprey_core <- function(grid, subs, NEIGHBORS, betaf, betas, delta) {
    .Call('caspr_predprey_core', PACKAGE = 'caspr', grid, subs, NEIGHBORS, betaf, betas, delta)
}

